spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: test
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect




logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE