spring:
  redis:
    host: 192.168.56.102
    password: 1234
    port: 6379

  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.56.101:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://192.168.56.102:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: test
    password: 123456
  thymeleaf:
    check-template-location: true
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    converters:
      preferred-json-mapper: gson




# spring boot의 기본 properties
server.error:
  include-exception: false # 응답에 exception의 내용을 포함할지 여부
  include-stacktrace: never # 오류 응답에 stacktrace 내용을 포함할 지 여부
  path: '/error' # 오류 응답을 처리할 핸들러(ErrorController)의 path
  whitelabel.enabled: true # 브라우저 요청에 대해 서버 오류시 기본으로 노출할 페이지를 사용할지 여부

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE